name: flutter_liquid_gooey_example
description: Example app demonstrating flutter_liquid_gooey features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_liquid_gooey:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  shaders:
    - ../shaders/liquid_gooey.frag
    - ../shaders/image_melt.frag
